root: true
parserOptions:
  requireConfigFile: false
  sourceType: module
  ecmaVersion: latest
env:
  webextensions: true
  browser: true
  es2022: true
extends:
  - airbnb-base
  - prettier
  - plugin:svelte/recommended
  - plugin:svelte/prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  sodium: readonly
  videojs: readonly
  process: readonly
overrides:
  - files:
      - '*.svelte'
      - '*.svelte.js'
    parser: svelte-eslint-parser
  - files:
      - src/lib/content/**/*.js
    rules:
      camelcase: off # FIXME
      no-console: off
rules:
  class-methods-use-this: off
  curly: ['error', 'all']
  eqeqeq: ['error', 'always'] # Disabled by Prettier
  import/extensions: off
  import/no-extraneous-dependencies: off
  import/no-mutable-exports: off
  import/no-unresolved: off
  import/prefer-default-export: off
  max-classes-per-file: off
  newline-before-return: error
  no-underscore-dangle: off
  # https://github.com/sveltejs/eslint-plugin-svelte#white_check_mark-rules
  svelte/no-at-html-tags: off
  # https://github.com/airbnb/javascript/issues/1660#issuecomment-353018874 + small tweaks
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: '*'
      next:
        - block
        - block-like
        - cjs-export
        - class
        - const
        - export
        - import
        - let
        - var
    - blankLine: always
      prev:
        - block
        - block-like
        - cjs-export
        - class
        - const
        - export
        - import
        - let
        - var
      next: '*'
    - blankLine: never
      prev:
        - singleline-const
        - singleline-let
        - singleline-var
      next:
        - singleline-const
        - singleline-let
        - singleline-var
    - blankLine: any
      prev:
        - export
        - import
      next:
        - export
        - import
