root: true
parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  sourceType: module
  ecmaVersion: 2020
env:
  webextensions: true
  browser: true
  es2022: true
extends:
  - eslint:recommended
  # - eslint-config-airbnb-base
  - prettier
plugins:
  - svelte3
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  sodium: readonly
  videojs: readonly
  process: readonly
overrides:
  - files:
      - '*.svelte'
    processor: svelte3/svelte3
