cooldown: 1
reject:
  # blocked by the ESLint v9 support of eslint-config-airbnb-base
  # https://github.com/airbnb/javascript/issues/2961
  - eslint
  - eslint-plugin-svelte
  # Pin @sveltia/ui to v0.35.6 because v0.36.0 switched from svelte-i18n to @sveltia/i18n
  - "@sveltia/ui"
  # Archiver 8.0.0 causes a build error
  - archiver
