version: "0.2"
language: en
dictionaries:
  - css
  - html
  - typescript
enableFiletypes:
  - ignore
  - properties
  - svelte
  - xml
files:
  - "**/.*"
  - "**/*.{css,js,json,jsonc,html,md,scss,svelte,svg,yaml,yml,xml}"
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
  - dist/**
words:
  - abema
  - abematv
  - afmt
  - Aichi
  - akamaized
  - amazonprimevideo
  - Aomori
  - atvwebplayersdk
  - autohide
  - automerge
  - bitrates
  - camelcase
  - clazz
  - corepack
  - dmkt
  - docomo
  - droprate
  - Ehime
  - eqeqeq
  - fluentd
  - Fmts
  - fpkey
  - fujitv
  - Fukui
  - Fukushima
  - googlevideo
  - gorin
  - Gunma
  - highres
  - Hyogo
  - Ibaraki
  - iijtwilightconcert
  - inittop
  - Ishikawa
  - itag
  - Iwate
  - Kagawa
  - Kanagawa
  - kbps
  - lemino
  - Mbps
  - mediainfo
  - Miyagi
  - Miyazaki
  - msgpack
  - netinfo
  - nhkondemand
  - nicolive
  - Niconico
  - nicovideo
  - nvweb
  - Oita
  - ondemand
  - packshot
  - paravi
  - playout
  - plmn
  - postcss
  - Saitama
  - serviceworker
  - Shiga
  - Shimane
  - simul
  - singleline
  - sparkline
  - streaksplayer
  - stylelint
  - sveltia
  - Tochigi
  - Tokushima
  - Tottori
  - TQAPI
  - Typecheck
  - uuidv
  - videojs
  - VideoMark
  - videoplayback
  - webextensions
  - wordmark
  - Yamaguchi
  - Yamanashi
  - ytplayer
