export default [
  {
    id: "youtube",
    name: "YouTube",
    url: "https://www.youtube.com/",
    brandcolor: "#cc0000",
    host: /(^|\.)youtube\.com$/,
  },
  {
    id: "netflix",
    name: "Netflix",
    url: "https://www.netflix.com/",
    brandcolor: "#b40710", // NOTE: #e50914 だがYouTubeと区別付かないので暗く
    host: /(^|\.)netflix\.com$/,
  },
  {
    id: "paravi",
    name: "Paravi",
    url: "https://www.paravi.jp/",
    brandcolor: "#004f99",
    host: /(^|\.)paravi\.jp$/,
  },
  {
    id: "tver",
    name: "TVer",
    url: "https://tver.jp/",
    brandcolor: "#40b8dc",
    host: /(^|\.)tver\.jp$/,
  },
  {
    id: "fod",
    name: "FOD",
    url: "https://fod.fujitv.co.jp/",
    brandcolor: "#800000",
    host: /(^|\.)fod\.fujitv\.co\.jp$/,
  },
  {
    id: "nicovideo",
    name: "ニコニコ動画",
    url: "https://www.nicovideo.jp/video_top",
    brandcolor: "#333333",
    host: /^www\.nicovideo\.jp$/,
  },
  {
    id: "nicolive",
    name: "ニコニコ生放送",
    url: "https://live.nicovideo.jp/",
    brandcolor: "#444444",
    host: /^live\d?\.nicovideo\.jp$/,
  },
  {
    id: "nhkondemand",
    name: "NHKオンデマンド",
    url: "https://www.nhk-ondemand.jp/",
    brandcolor: "#f18b02",
    host: /(^|\.)nhk-ondemand\.jp$/,
  },
  {
    id: "dtv",
    name: "dTV",
    url: "https://pc.video.dmkt-sp.jp/",
    brandcolor: "#CC6680",
    host: /(^|\.)video\.dmkt-sp\.jp$/,
  },
  {
    id: "abematv",
    name: "AbemaTV",
    url: "https://abema.tv/",
    brandcolor: "#33AA22",
    host: /^abema\.tv$/,
  },
  {
    id: "amazonprimevideo",
    name: "Amazon Prime Video",
    url: "https://www.amazon.co.jp/PrimeVideo",
    brandcolor: "#015A80",
    host: /(^|\.)amazon\.co\.jp$/,
  },
  {
    id: "iijtwilightconcert",
    experimental: true,
    name: "TWILIGHT CONCERT",
    brandcolor: "#CCB42B",
    host: /^pr\.iij\.ad\.jp$/,
  },
  {
    id: "jwplayer",
    experimental: true,
    name: "JWPlayer",
    brandcolor: "#CCB42B",
    // https://www.oreilly.com/library/view/regular-expressions-cookbook/9780596802837/ch07s16.html
    host: /^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/,
  },
  {
    id: "gorin",
    name: "gorin.jp",
    url: "https://www.gorin.jp//",
    brandcolor: "#40b8dc",
    host: /(^|\.)gorin\.jp$/,
  },
];
